name: maxi_library
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  rxdart: ^0.28.0
  meta: ^1.15.0
  http: ^1.2.2
  analyzer: ^8.1.1
  collection: ^1.18.0
  web_socket_channel: ^3.0.1
  deepseek: ^1.2.0
  xml: ^6.5.0
  #csv: ^6.0.0
  #async: ^2.13.0
  
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  
