name: maxi_library
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  rxdart: ^0.28.0
  reflectable: ^4.0.9
  meta: ^1.15.0
  collection: ^1.19.0
  http: ^1.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
